/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-8-7: 15h:41m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "hiredis/hiredis.h"

#include "libc/sys/CATS/time.cats"

#include "libc/CATS/fcntl.cats"

#include "libc/sys/CATS/types.cats"

#include "libc/sys/CATS/types.cats"

#include "libc/CATS/stdarg.cats"
/* external codes at top */


char *redisReplyGetString (redisReply *reply) {
	return reply->str;
}

long long redisReplyGetInteger (redisReply *reply) {
	return reply->integer;
}



int pointerIsNull (void *ptr) {
	return ptr == NULL;
}

int pointerIsNotNull (void *ptr) {
	return ptr != NULL;
}



#include <stdarg.h>

redisReply *redisCommandHandler (redisContext *ctx, char *fmt, ...) {
	va_list args;
	va_start (args, fmt);
	redisReply *reply = redisvCommand (ctx, fmt, args);
	va_end (args);
	return reply;
}

int redisAppendCommandHandler (redisContext *ctx, char *fmt, ...) {
	va_list args;
	va_start (args, fmt);
	int ret = redisvAppendCommand (ctx, fmt, args);
	va_end (args);
	return ret;
}

int redisFormatCommandHandler (void **target, char *fmt, ...) {
	va_list args;
	va_start (args, fmt);
	int ret = redisvFormatCommand ((char **)target, fmt, args);
	va_end (args);
	return ret;
}


/* type definitions */
/* external typedefs */
/* external dynamic constructor declarations */
/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_assert) (ats_bool_type) ;
ATSextern_fun(ats_void_type, atspre_printf_exn) (ats_ptr_type, ...) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
int _2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2esats__sasp__redisReply = 0 ;

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwwu/Workspace/ats-redis/helloworld/redis.dats: 109(line=7, offs=6) -- 945(line=34, offs=4)
*/
ATSglobaldec()
ats_void_type
mainats () {
/* local vardec */
// ATSlocal_void (tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;
// ATSlocal_void (tmp2) ;
ATSlocal (ats_bool_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;
ATSlocal (ats_ptr_type, tmp5) ;
// ATSlocal_void (tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;
// ATSlocal_void (tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_int_type, tmp10) ;
// ATSlocal_void (tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;
// ATSlocal_void (tmp13) ;
ATSlocal (ats_bool_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
ATSlocal (ats_int_type, tmp16) ;
// ATSlocal_void (tmp17) ;
// ATSlocal_void (tmp18) ;
ATSlocal (ats_bool_type, tmp19) ;
// ATSlocal_void (tmp20) ;

__ats_lab_mainats:
tmp1 = redisConnect (ATSstrcst("127.0.0.1"), 6379) ;
tmp3 = pointerIsNotNull (tmp1) ;
/* tmp2 = */ atspre_assert (tmp3) ;
tmp4 = redisCommandHandler (tmp1, ATSstrcst("ping")) ;
tmp5 = redisReplyGetString (tmp4) ;
/* tmp6 = */ freeReplyObject (tmp4) ;
tmp7 = redisCommandHandler (tmp1, ATSstrcst("SET %s %s"), ATSstrcst("bar"), ATSstrcst("hello")) ;
/* tmp8 = */ freeReplyObject (tmp7) ;
/* ats_ptr_type tmp9 ; */
tmp10 = redisFormatCommandHandler ((&tmp9), ATSstrcst("SET %s %s"), ATSstrcst("bar"), ATSstrcst("hello")) ;
/* tmp11 = */ atspre_printf_exn (ATSstrcst("TARGET: %s\nEND\n"), tmp9) ;
tmp12 = redisReaderCreate () ;
tmp14 = pointerIsNotNull (tmp12) ;
/* tmp13 = */ atspre_assert (tmp14) ;
/* ats_ptr_type tmp15 ; */
tmp16 = redisReaderGetReply (tmp12, (&tmp15)) ;
/* tmp17 = */ redisReaderFree (tmp12) ;
tmp19 = pointerIsNotNull (tmp15) ;
/* tmp18 = */ atspre_assert (tmp19) ;
/* tmp20 = */ freeReplyObject (tmp15) ;
/* tmp0 = */ redisFree (tmp1) ;
return /* (tmp0) */ ;
} /* end of [mainats] */

/* static load function */

extern ats_void_type _2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2libc_2SATS_2stdarg_2esats__staload (void) ;

ats_void_type
_2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2edats__staload () {
static int _2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2edats__staload_flag = 0 ;
if (_2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2edats__staload_flag) return ;
_2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2edats__staload_flag = 1 ;

_2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2esats__staload () ;
ATS_2d0_2e2_2e10_2libc_2SATS_2stdarg_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
// extern ats_int_type _2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2edats__dynload_flag ;

ats_void_type
_2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2edats__dynload () {
// _2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2edats__dynload_flag = 1 ;
_2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

int main (int argc, char *argv[]) {
ATS_GC_INIT() ;
mainats_prelude() ;
_2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2edats__dynload() ;
mainats((ats_int_type)argc, (ats_ptr_type)argv) ;
return (0) ;
} /* end of main */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [redis_dats.c] */
