/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-8-7: 15h:41m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* prologues from statically loaded files */

#include "libc/sys/CATS/time.cats"

#include "libc/CATS/fcntl.cats"

#include "libc/sys/CATS/types.cats"

#include "libc/sys/CATS/types.cats"
/* external codes at top */

#include "hiredis/hiredis.h"

/* type definitions */
/* external typedefs */
/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* static load function */

extern ats_void_type ATS_2d0_2e2_2e10_2libc_2sys_2SATS_2time_2esats__staload (void) ;

ats_void_type
_2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2esats__staload () {
static int _2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2esats__staload_flag = 0 ;
if (_2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2esats__staload_flag) return ;
_2home_2hwwu_2Workspace_2ats_2dredis_2helloworld_2redis_2esats__staload_flag = 1 ;

ATS_2d0_2e2_2e10_2libc_2sys_2SATS_2time_2esats__staload () ;

return ;
} /* staload function */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [redis_sats.c] */
